name: PR Build Validation

on:
  pull_request:
    branches: [ main ]  # 目标分支（按需修改）
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'  # 启用缓存，加快 CI

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run docs:build
