name: PR Description Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Description
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            // 匹配 PR 描述部分的正则表达式
            const prDescriptionSection = pr.body.match(/## PR Description\s*([\s\S]*?)(?=##|\n##|$)/i);
            
            if (prDescriptionSection) {
              const content = prDescriptionSection[1].trim();
              // 检查内容是否为空或只有注释
              if (!content || content === '<!-- 请清晰描述本次 PR 的具体内容及目的。 -->') {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  body: '⚠️ 请补充 PR 描述内容！请在 **PR Description** 部分详细说明本次修改的内容和目的。'
                });
              }
            }