name: Update Markdown Frontmatter

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-frontmatter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 添加 createdDate
      - name: Add createdDate
        run: python scripts/add_created_date_to_md.py

      # 添加 lastUpdated
      - name: Add or Update lastUpdated
        run: python scripts/add_last_updated_to_md.py

      # 提交修改
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/**/*.md
          git commit -m "chore: update createdDate and lastUpdated in md files" || echo "No changes to commit"

      # 推送回 PR 分支
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.head_ref }}
